export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL"
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS ="LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const GET_DISCUSS_POSTS = "GET_DISCUSS_POSTS"
export const GET_DISCUSS_POST = "GET_DISCUSS_POST"
export const DISCUSS_POST_ERROR = "DISCUSS_POST_ERROR"
export const ADD_DISCUSS_POST = "ADD_DISCUSS_POST"
export const ADD_DISCUSS_COMMENT = "ADD_DISCUSS_COMMENT"

export const ADD_RESOURCE = "ADD_RESOURCE"
export const RESOURCE_ERROR = "RESOURCE_ERROR"
export const GET_ALL_RESOURCES = "GET_ALL_RESOURCES"

export const ADD_SHOWCASE_POST = "ADD_SHOWCASE_POST"
export const GET_SHOWCASE_POSTS = "GET_SHOWCASE_POSTS"
export const SHOWCASE_POST_ERROR = "SHOWCASE_POST_ERROR"
export const GET_SHOWCASE_POST = "GET_SHOWCASE_POST"
export const ADD_FEEDBACK = "ADD_FEEDBACK"



